package com.eshanren.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRobot<M extends BaseRobot<M>> extends Model<M> implements IBean {

	public void setRobotId(java.lang.Integer robotId) {
		set("robot_id", robotId);
	}
	
	public java.lang.Integer getRobotId() {
		return getInt("robot_id");
	}

	public void setRobotName(java.lang.String robotName) {
		set("robot_name", robotName);
	}
	
	public java.lang.String getRobotName() {
		return getStr("robot_name");
	}

	public void setRobotUrl(java.lang.String robotUrl) {
		set("robot_url", robotUrl);
	}
	
	public java.lang.String getRobotUrl() {
		return getStr("robot_url");
	}

}
