package com.eshanren.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public void setAdminId(java.lang.Integer adminId) {
		set("admin_id", adminId);
	}
	
	public java.lang.Integer getAdminId() {
		return getInt("admin_id");
	}

	public void setAdminName(java.lang.String adminName) {
		set("admin_name", adminName);
	}
	
	public java.lang.String getAdminName() {
		return getStr("admin_name");
	}

	public void setAdminPassword(java.lang.String adminPassword) {
		set("admin_password", adminPassword);
	}
	
	public java.lang.String getAdminPassword() {
		return getStr("admin_password");
	}

	public void setAdminLogintime(java.lang.Long adminLogintime) {
		set("admin_logintime", adminLogintime);
	}
	
	public java.lang.Long getAdminLogintime() {
		return getLong("admin_logintime");
	}

}
